services:
  - type: web
    name: prometheus
    env: docker
    dockerfilePath: infra/prometheus/Dockerfile
    plan: free

  - type: web
    name: grafana
    env: docker
    dockerfilePath: infra/grafana/Dockerfile
    plan: free
    envVars:
      - key: GF_SECURITY_ADMIN_USER
        value: "admin"
      - key: GF_SECURITY_ADMIN_PASSWORD
        value: "admin"
