name: CI/CD Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --eval 'db.adminCommand(\"ping\")'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      PORT: 3000
      MONGO_URI_PROD: ${{ secrets.MONGO_URI_PROD }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependências
        run: npm install

      - name: Garantir permissão de execução para jest
        run: chmod +x ./node_modules/.bin/jest

      - name: Rodar testes com cobertura
        run: |
          npx jest --coverage --coverageReporters=text-summary > coverage.txt
          cat coverage.txt

          COVERAGE=$(grep -Po '^Statements\s*:\s*\K[0-9]+' coverage.txt)
          echo "Cobertura total: $COVERAGE%"
          if [ "$COVERAGE" -lt 20 ]; then
            echo "❌ Cobertura abaixo de 20%"
            exit 1
          else
            echo "✅ Cobertura aceitável"
          fi

      - name: Roda testes mutantes
        run: |
          chmod +x ./node_modules/.bin/stryker
          npx stryker run

      - name: Verificar versão do Docker
        run: docker --version

      - name: Build da imagem Docker
        run: docker build -t techblog-api .

      - name: Subir container da API
        run: |
          docker run -d -p 3000:3000 \
            -e MONGO_URI_PROD=${{ secrets.MONGO_URI_PROD }} \
            -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
            --name techblog-api \
            techblog-api

      - name: Limpeza do container
        if: always()
        run: |
          docker stop techblog-api || true
          docker rm techblog-api || true

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Trigger Render Deploy
        env:
          RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          if [ -z "$RENDER_DEPLOY_HOOK_URL" ]; then
            echo "❌ Variável de ambiente RENDER_DEPLOY_HOOK_URL não configurada!"
            exit 1
          fi
          curl -X POST "$RENDER_DEPLOY_HOOK_URL"
